import { TaxState } from './types';

export const initialState: TaxState = {
  currentStep: 0,
  anneeDeclaration: 2026,
  modules: {
    salaires: false,
    retraite: false,
    independant: false,
    locationNue: false,
    locationMeublee: false,
    sci: false,
    patrimoinefinancier: false,
    plusValues: false,
    chargesDeductibles: false,
  },
  situationPersonnelle: {
    situationMaritale: 'celibataire',
    anneeNaissanceDeclarant: '',
    anneeNaissanceConjoint: '',
    enfants: [],
    parentIsole: false,
    invalide: false,
    ancienCombattant: false,
    invalideConjoint: false,
  },
  revenusSalariaux: {
    declarant: {
      salaires: 0,
      avantagesNature: 0,
      heuresSup: 0,
      fraisPro: 'forfait',
      fraisReels: {
        km: 0,
        typeVehicule: 'voiture',
        cylindree: '5cv',
        repas: 0,
        formation: 0,
        doubleResidence: 0,
        autresFrais: 0,
      },
    },
    conjoint: {
      salaires: 0,
      avantagesNature: 0,
      heuresSup: 0,
      fraisPro: 'forfait',
      fraisReels: {
        km: 0,
        typeVehicule: 'voiture',
        cylindree: '5cv',
        repas: 0,
        formation: 0,
        doubleResidence: 0,
        autresFrais: 0,
      },
    },
  },
  revenusRemplacement: {
    declarant: {
      chomage: 0,
      indemMaladie: 0,
      retraite: 0,
      invalidite: 0,
      indemLicenciement: 0,
      renteViagere: 0,
      ageRenteViagere: 70,
    },
    conjoint: {
      chomage: 0,
      indemMaladie: 0,
      retraite: 0,
      invalidite: 0,
      indemLicenciement: 0,
      renteViagere: 0,
      ageRenteViagere: 70,
    },
  },
  revenusIndependant: {
    microEntreprise: {
      actif: false,
      typeActivite: null,
      chiffreAffaires: 0,
      versementLiberatoire: false,
    },
    reel: {
      actif: false,
      typeFiscal: 'bnc',
      resultatNet: 0,
      deficit: 0,
    },
    gerantSarl: {
      actif: false,
      remuneration: 0,
      fraisPro: 'forfait',
    },
  },
  revenusFonciers: {
    regime: null,
    recettes: {
      loyersNus: 0,
      chargesRecuperees: 0,
      subventionsANAH: 0,
    },
    charges: {
      chargesCopro: 0,
      chargesRecupereesSurLocataire: 0,
      interetsEmprunt: 0,
      assuranceADI: 0,
      fraisGarantie: 0,
      mainleveeHypotheque: 0,
      assurancePNO: 0,
      assuranceGLI: 0,
      taxeFonciere: 0,
      teomRecuperee: false,
      fraisGestionAgence: 0,
      fraisGestionDirect: 0,
      fraisGestionDirectNbLocaux: 1,
      fraisProcedure: 0,
      travauxEntretien: 0,
      travauxAmelioration: 0,
    },
    deficitAnterieurs: 0,
    microFoncierCA: 0,
  },
  revenusLMNP: {
    statut: 'lmnp',
    regime: null,
    recettes: 0,
    charges: {
      chargesCopro: 0,
      interetsEmprunt: 0,
      assuranceADI: 0,
      assurancePNO: 0,
      taxeFonciere: 0,
      fraisGestion: 0,
      travauxEntretien: 0,
      amortissementBien: 0,
      amortissementMobilier: 0,
      amortissementTravaux: 0,
    },
  },
  revenusSCI: {
    quotePartResultat: 0,
    quotePartDeficit: 0,
    typeSCI: 'ir',
  },
  revenusPatrimoine: {
    interets: 0,
    dividendes: 0,
    revenusDistribuesFCP: 0,
    avoirFiscal: 0,
    optionBarem: false,
    csgDeductible: 0,
    plusValuesMobilieres: 0,
    moinsValuesMobilieres: 0,
    plusValueImmobiliere: 0,
    assuranceVieCt8ans: 0,
    assuranceVieMt8ans: 0,
  },
  chargesDeductibles: {
    pensionEnfantMajeur: 0,
    pensionExConjoint: 0,
    pensionParents: 0,
    versementsPER: 0,
    versementsPERP: 0,
    versementsMadelin: 0,
    csgDeductible: 0,
    deficitFoncierAnterieur: 0,
  },
  reductionsCreditImpot: {
    donsAssociations: 0,
    donsUrgence: 0,
    donsPartis: 0,
    emploiDomicile: 0,
    gardeEnfant1: 0,
    gardeEnfant2: 0,
    gardeEnfant3: 0,
    enfantsCollege: 0,
    enfantsLycee: 0,
    enfantsSup: 0,
    investPinel: 0,
    investPME: 0,
    investFCPI: 0,
    cotisationsSyndicales: 0,
    fraisComptabilite: 0,
  },
  ifi: {
    assujetti: false,
    valeurBrute: 0,
    passifDeductible: 0,
  },
};
